6609650228

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/CS240/employees.csv")

In [ ]:
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
data.shape

(1000, 8)

In [ ]:
data.duplicated(data[["First Name" , "Gender" , "Team"]])

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
data[data['First Name'] == "Henry"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
57,Henry,Male,6/26/1996,1:44 AM,64715,15.107,True,Human Resources
136,Henry,Male,4/24/1995,4:18 AM,43542,19.687,False,Legal
259,Henry,Male,2/6/1995,8:34 AM,89258,15.585,True,Human Resources
732,Henry,Male,5/12/1986,2:04 AM,59943,1.432,False,Finance
752,Henry,Male,2/23/2007,3:24 AM,49665,18.338,False,Business Development
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution

In [ ]:
henry = data[data['First Name'] == "Henry"]

In [ ]:
henry

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
57,Henry,Male,6/26/1996,1:44 AM,64715,15.107,True,Human Resources
136,Henry,Male,4/24/1995,4:18 AM,43542,19.687,False,Legal
259,Henry,Male,2/6/1995,8:34 AM,89258,15.585,True,Human Resources
732,Henry,Male,5/12/1986,2:04 AM,59943,1.432,False,Finance
752,Henry,Male,2/23/2007,3:24 AM,49665,18.338,False,Business Development
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution

In [ ]:
henry.shape

(6, 8)